version: "3.3"
services:

    db:
        image: SQL_IMAGE
        container_name: db_dev_env
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_dev_env
        restart: always
        depends_on:
            - db
        ports:
            - PMA_PORT:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        build: maildev
        container_name: maildev_dev_env
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - MAILDEV_PORT:80
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: www_dev_env
        ports:
          - WWW_PORT:80
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:

