version: "3.3"
services:

    db:
        image: mysql:latest
        container_name: db_dev_env
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_dev_env
        restart: always
        depends_on:
            - db
        ports:
            - PMA_PORT:80
        environment:
            PMA_HOST: db
        networks:
            - dev
    maildev:
        image: maildev/maildev
        restart: always
        environment:
            - TZ=Europe/paris
            - MAILDEV_WEB_PORT=1080
            - MAILDEV_SMTP_PORT=1025
        ports:
            - "MAILDEV_PORT:1080"
            - "25:1025"
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
        networks:
            - dev
    www:
        build: 
            context: .
            dockerfile: www/Dockerfile
        container_name: www_dev_env
        ports:
          - WWW_PORT:80
        volumes:
            - ./www/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:

